### ISSUE TITLE
Vagrantfile

### ISSUE THREAD

**Issue by scottcrespo** [OrlandoGolang/eps-conduit#25]
@picardrulez 

We could really use a Vagrantfile to make it easy for others to develop and run test for eps-conduit
### Proposed Features:
- ubuntu/trust64 base box
- Go 1.5.1
- "Hello World" web app, runnable as multiple processes, and integrated with eps-conduit to test/validate load balancer

**Comment by scottcrespo** [comment]
@dansackett @picardrulez @msardo @etse-topps 

Vagrant machine appears to provisioning properly. Can other folks begin testing the `release/vagrant` branch and post their results here? Simply follow the Installation Instructions in the README

**Comment by dansackett** [comment]
@scottcrespo looks like everything works as you described it. Only thing I'd say is remove the line for `vagrant provision` from the README since a typical `vagrant up` provisions for you already. Otherwise:

```
==> default: Chef Client finished, 30/30 resources updated in 56 seconds
```

And the CURL calls:

```
$ curl localhost:8000
Hello world, I'm answering your request from backend port 8001
$ curl localhost:8000
Hello world, I'm answering your request from backend port 8002
```

Nice work!

**Comment by scottcrespo** [comment]
@dansackett 

Made the change to the README you recommended. Just have to wait on a few more to confirm the  results, and I'll issue a PR against `develop`

**Comment by etse-topps** [comment]
Same results here as @dansackett.  Noticed that CompileDaemon running on the vagrant box wasn't picking up on file changes though.

**Comment by scottcrespo** [comment]
@etse-topps 

Good catch. CompileDaemon probably can't recognize file changes due to how vagrant sync's directories from the host machine.

I removed compile daemon from the recipes, and re-ran the test scenario successfully
